//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryType
    {
        public byte ID { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
    }
}
