//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScooterPhoto
    {
        public short ID { get; set; }
        public int ScooterID { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Scooter Scooter { get; set; }
    }
}
